language: minimal
dist: bionic
env:
- resume_fodder_download=https://sourceforge.net/projects/resumefodder/files/ResumeFodder-1.0/Linux-64bit/ResumeFodder-1.0-linux64.tar.gz/download
- resume_fodder_template=/tmp/ResumeFodder/templates/refined.xml

before_install:
- wget -O /tmp/ResumeFodder.tar.gz ${resume_fodder_download}
- tar xf /tmp/ResumeFodder.tar.gz -C /tmp

script:
- "/tmp/ResumeFodder/ResumeFodder export resume.json resume.doc ${resume_fodder_template}"
- |
  curl -f -L "https://api.cloudconvert.com/v1/convert" \
  -F file=@"resume.doc" \
  -F "apikey=$cloudconvert_api_key" \
  -F "inputformat=doc" \
  -F "outputformat=pdf" \
  -F "input=upload" \
  -F "wait=true" \
  -F "download=inline" \
  > "resume.pdf"
- |
  curl -f -L "https://api.cloudconvert.com/v1/convert" \
  -F file=@"resume.doc" \
  -F "apikey=$cloudconvert_api_key" \
  -F "inputformat=doc" \
  -F "outputformat=docx" \
  -F "input=upload" \
  -F "wait=true" \
  -F "download=inline" \
  > "resume.docx"

before_deploy:
  - chmod ugo+x ./move_pr_build.sh
  - ./move_pr_build.sh

deploy:
  provider: gcs
  access_key_id: GOOG7WAZE6SKMBYAPX4DOZYK
  secret_access_key:
    secure: rdj4TdM1FdqASVWzbQt47VP3LPic9T2b6ZUQmFxaa/qXosYhw0eLlB/tSGVibzmzrKDuM0bJM17LfuL2TFxDtSQ88AIhlErB/CYx8VWF2vESmEcEQw5HS48QHNPazrtnFi7eVCsFTLN+SoIRbZSCAqE9ENG7mV7gnap8WwnSep7u1bW42re7uWHdRiC6BNwmapdsqwTeVmN3khCGw0xqm2gpON6rQtQ8hb4b8c2FMBJLYM3ituoMidi99wVem06CEmeFG13yperciH4Lb+J/cxF2zTWSzM0c9Ne+2HsfuG6mkjpMpR1erEkt+2vPGs9PFOlldIzsCwVC3N9JUpZvtAcQYrqIcUTtDAV6UrdUfRdAmGEtR7DYMYK6K1qaP+gGrS2uIK+b0VnoJGC1jBgLVSlh5aPVeC7GfG4eEShMuQzsNCjPodu8WdjcPmGqFqxXUUzlgC8ZzfcTyrBMi/gcK2ek52Zgd35Nt8A/X5o+V8Z66z6CnepzBFltwaX4dP0bDr+R0ZqapZdIz7KWXMV++R3oc5HkXHeeLaygG+Hx7BmvuIlqIJtkJl9UrgrgvfGKEz2B9lA51tRTuGbs1gFQBZXuJlI5n+v+IPNmx8t9ZI1IskZJy1H1OChr7Ys9QFg9SzWk5z7ulApOAgxlKth5XisnE7CRyfE8Zmjj7gcGnSA=
  bucket: alisonc-resume.appspot.com
  local-dir: build
  skip_cleanup: true
  acl: public-read
  on:
    all_branches: true
